CREATE TABLE `orders` (
  `orders_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'order_id',
  `orders_code` varchar(32) NOT NULL DEFAULT '' COMMENT '订单编码',
  `cq_id` int(11) NOT NULL DEFAULT '0' COMMENT '表customer_questions的主键id',
  `ebay_code` varchar(128) NOT NULL DEFAULT '' COMMENT 'EBAY订单号',
  `recordnumber` int(11) NOT NULL COMMENT '站点的订单序号',
  `orders_user_id` varchar(128) NOT NULL DEFAULT '' COMMENT '参照用户ID:网站用户ID/EBAY用户ID',
  `site_id` varchar(64) NOT NULL DEFAULT '' COMMENT '订单来源站点ID',
  `order_user_email` varchar(100) NOT NULL DEFAULT '' COMMENT '订单用户EMAIL',
  `bill_first_name` varchar(50) NOT NULL DEFAULT '' COMMENT '帐单FIRST NAME',
  `bill_last_name` varchar(50) NOT NULL DEFAULT '' COMMENT '帐单LAST NAME',
  `bill_company` varchar(255) NOT NULL DEFAULT '' COMMENT '帐单公司名称',
  `bill_street1` varchar(255) NOT NULL DEFAULT '' COMMENT '帐单地址1',
  `bill_street2` varchar(255) NOT NULL DEFAULT '' COMMENT '帐单地址2',
  `bill_city` varchar(100) NOT NULL DEFAULT '' COMMENT '帐单城市',
  `bill_state` varchar(100) NOT NULL DEFAULT '' COMMENT '帐单省/州',
  `bill_zip` varchar(50) NOT NULL DEFAULT '' COMMENT '帐单邮编',
  `bill_country` varchar(50) NOT NULL DEFAULT '' COMMENT '''帐单国家',
  `bill_country_id` int(11) NOT NULL DEFAULT '0' COMMENT 'bill country系统对应国家ID',
  `bill_phone` varchar(50) NOT NULL DEFAULT '' COMMENT '帐单电话',
  `bill_fax` varchar(50) NOT NULL DEFAULT '' COMMENT '传真',
  `ship_first_name` varchar(50) NOT NULL DEFAULT '' COMMENT '收件人FIRST NAME',
  `ship_last_name` varchar(50) NOT NULL DEFAULT '' COMMENT '收件人LAST NAME',
  `ship_company` varchar(255) NOT NULL DEFAULT '' COMMENT '收件人公司名称',
  `ship_street1` varchar(255) NOT NULL COMMENT '收件人地址1',
  `ship_street2` varchar(255) NOT NULL DEFAULT '' COMMENT '收件人地址2''',
  `ship_city` varchar(100) NOT NULL DEFAULT '' COMMENT '收件人城市',
  `ship_state` varchar(100) NOT NULL DEFAULT '' COMMENT '收件人省/州',
  `ship_zip` varchar(50) NOT NULL DEFAULT '' COMMENT '收件人邮编',
  `ship_country` varchar(50) NOT NULL DEFAULT '' COMMENT '收件人国家',
  `ship_country_id` int(11) NOT NULL DEFAULT '0' COMMENT 'ship country系统对应国家ID',
  `ship_phone` varchar(50) NOT NULL DEFAULT '' COMMENT '收件人电话',
  `ship_fax` varchar(50) NOT NULL DEFAULT '' COMMENT '传真',
  `taxes_number` varchar(255) NOT NULL DEFAULT '' COMMENT '税号',
  `ebay_create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'eBay下单时间',
  `date_placed` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '订单创建时间',
  `date_ship` datetime NOT NULL COMMENT 'CFF出库日期',
  `sfc_date_ship` datetime NOT NULL COMMENT 'SFC发货日期',
  `date_finished` datetime NOT NULL COMMENT '订单结束时间',
  `date_payment` datetime NOT NULL COMMENT '支付时间',
  `ebay_last_update` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '亚马逊订单最后发货期限',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '订单创建时间',
  `orders_status` varchar(10) NOT NULL DEFAULT 'download' COMMENT '订单状态:download(已下载或已生成),OP(订单处理中),OC(取消),OD(已完成)',
  `orders_status_payment` char(4) NOT NULL DEFAULT 'PU' COMMENT '订单支付状态:PU(未付款),PS(已提交)，PD（已支付）',
  `orders_status_process` tinyint(3) NOT NULL DEFAULT '0' COMMENT '订单处理状态:0末开始处理,1订单信息验证通过,2支付验证通过,3已导入CFF,4(Ready to Print),5(Ready to Ship),6已导入物流,7 SFC Shipped,8(On Hold),9 CFF Shipped',
  `orders_status_underreview` tinyint(3) NOT NULL DEFAULT '0' COMMENT 'underreview状态类型',
  `orders_status_shipping` char(4) NOT NULL DEFAULT 'SU' COMMENT '订单运输状态：SU(未运输),SD(已发货),SS(已交际)',
  `orders_status_return` varchar(10) NOT NULL DEFAULT 'RU' COMMENT '订单退货状态:RU(无退货),RS(已退货),RD(已退货)',
  `currencies_id` int(11) NOT NULL DEFAULT '0' COMMENT '订单货币ID',
  `currency_rate` decimal(8,4) NOT NULL DEFAULT '0.0000' COMMENT '订单货币当前汇率',
  `subtotal` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单金额',
  `shipping_cost` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单运输成本',
  `wrapping_cost` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单包装成本',
  `orders_weight` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT '订单重量',
  `orders_cff_weight` decimal(7,2) NOT NULL DEFAULT '0.00' COMMENT 'CFF订单重量',
  `orders_ship_fee` decimal(8,2) DEFAULT NULL COMMENT '物流运费',
  `order_handle_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '订单处理费',
  `order_package_fee` decimal(8,2) DEFAULT '0.00' COMMENT '包材费',
  `sfc_ship_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'SFC订单运费',
  `sfc_vat_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'SFC VAT 费',
  `sfc_currency` varchar(12) NOT NULL DEFAULT '0.00' COMMENT 'SFC VAT 币种',
  `declared_value` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '申报价值',
  `tax` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单税费',
  `insurance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'IInsurance，保险费用',
  `orders_discount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `orders_vat_discount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '申报价值折扣',
  `grand_total` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `coupon_code` varchar(25) NOT NULL DEFAULT '' COMMENT '优惠卷',
  `coupon_discount_value` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '优惠卷金额',
  `point_discount_value` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '积分优惠金额',
  `point_value` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '积分',
  `shipping_method` varchar(100) NOT NULL DEFAULT '' COMMENT '运输方式',
  `shipping_method_orig` varchar(128) NOT NULL DEFAULT '' COMMENT '原始运输方式',
  `track_number` varchar(200) NOT NULL DEFAULT '' COMMENT '跟踪号',
  `track_number1` varchar(200) NOT NULL DEFAULT '' COMMENT 'SFC分包单号',
  `follow_number` varchar(200) NOT NULL DEFAULT '' COMMENT '真正的跟踪号',
  `of_id` int(11) NOT NULL DEFAULT '0',
  `orders_fraud` tinyint(2) NOT NULL DEFAULT '0' COMMENT 'Fraud 标志',
  `print_time` datetime NOT NULL COMMENT '打印时间',
  `dispute_platform` varchar(32) NOT NULL DEFAULT '' COMMENT '需要信用卡',
  `dispute` tinyint(2) NOT NULL DEFAULT '0' COMMENT '争论',
  `dispute_id` varchar(64) NOT NULL DEFAULT '',
  `orders_type` enum('create','download') NOT NULL DEFAULT 'download' COMMENT '单订创建类型',
  `warehouse_room_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0:一般;1:贵重;',
  `orders_create_user_id` int(11) NOT NULL COMMENT '创建订单用户ID',
  `transaction_number` varchar(128) NOT NULL COMMENT '交易号',
  `transaction_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '交易费',
  `wr_name` varchar(15) NOT NULL COMMENT '区域名称',
  `orders_picking_user_name` varchar(50) NOT NULL DEFAULT '' COMMENT '配货员姓名',
  `orders_sort_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `print_sort_id` varchar(32) DEFAULT NULL COMMENT '打印排序ID',
  `shipped_remark` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否已经把Ebay的状态标志成已shippedment',
  `is_update_track` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否已经把SFC追踪号上传到Ebay',
  `update_track_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '追踪号上传时间',
  `orders_wait` tinyint(3) NOT NULL DEFAULT '0' COMMENT '标记是否愿意等',
  `orders_send` tinyint(3) NOT NULL DEFAULT '0' COMMENT '标记是否发送过邮件',
  `dz_of_id` int(10) DEFAULT '0' COMMENT '是否含有定制产品标记',
  `cff_code` varchar(32) NOT NULL DEFAULT '' COMMENT 'CFF订单号',
  `cff_estimate_weight` decimal(7,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'CFF预估重量',
  `cff_create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '导入CFF的时间',
  `drivered_time` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '离港时间',
  `delivered_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'EPACKET Delivered Time',
  `follow_number1` varchar(50) NOT NULL DEFAULT '' COMMENT '物流转运单号',
  `follow_number1_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '物流转运单时间',
  `sfc_work_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '扣费工作日',
  `is_urgent` tinyint(4) NOT NULL DEFAULT '0' COMMENT '紧急SORT',
  `orders_scf_checked` enum('Y','N') DEFAULT 'N' COMMENT '是否对过的，是否做过标记，是否标记已核销(Y:是;N:否)',
  `warehouse_id` int(11) NOT NULL DEFAULT '1' COMMENT '仓库ID',
  `reship_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1分单，2 重寄',
  `feedback_revision` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT 'feedback是否已撤评',
  `feedback_status` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT 'feedback是否Removed',
  `sub_orders_code` varchar(255) NOT NULL DEFAULT '' COMMENT '关联(子)订单号',
  `is_remote` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否偏远地区,1:是 0:否',
  `orders_batter` enum('Y','N','I') DEFAULT 'N' COMMENT 'Y:纯电池; N:不是电池; I:含电池',
  `orders_metal` enum('Y','N') DEFAULT 'N' COMMENT 'Y:金属; N:非金属',
  `print_special_labels` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT '是否打印特殊地址标签 Y:是; N:否',
  `orders_led` enum('Y','N') DEFAULT 'N' COMMENT 'Y: LED, N不是',
  `shipping_method_forbid` varchar(255) NOT NULL DEFAULT '' COMMENT '禁运运输方式',
  `orders_sku_property` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '订单SKU属性,1:一票一件一个数量 2:一票一件多数量 3:一票多件',
  `consumables_ids` varchar(30) DEFAULT NULL COMMENT '耗材ID，多个时用'',''分隔',
  `chargebackTime` datetime NOT NULL COMMENT 'SFC扣费实际时间',
  `user_identifier` varchar(32) NOT NULL DEFAULT '' COMMENT '用户身份标识号',
  PRIMARY KEY (`orders_id`,`create_time`,`chargebackTime`),
  KEY `orders_code_i` (`orders_code`),
  KEY `order_user_email` (`order_user_email`),
  KEY `orders_user_id` (`orders_user_id`),
  KEY `ship_first_name` (`ship_first_name`,`ship_last_name`),
  KEY `date_ship` (`date_ship`),
  KEY `index_transaction_number` (`transaction_number`),
  KEY `orders_create_time_i` (`create_time`),
  KEY `orders_sort_date` (`orders_sort_date`),
  KEY `orders_status` (`orders_status`,`orders_status_process`,`orders_status_underreview`),
  KEY `shipping_method` (`shipping_method`),
  KEY `site_id_recordnumber` (`site_id`,`recordnumber`),
  KEY `date_placed` (`date_placed`),
  KEY `track_number` (`track_number`),
  KEY `ebay_code` (`ebay_code`(30)),
  KEY `last_update_index` (`last_update`),
  KEY `index_charge` (`chargebackTime`),
  KEY `cff_code` (`cff_code`),
  KEY `site_update_track` (`site_id`,`is_update_track`)
) ENGINE=InnoDB AUTO_INCREMENT=1769777694 DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (to_days(create_time))
(PARTITION pbegin VALUES LESS THAN (734868) ENGINE = InnoDB,
 PARTITION p201201 VALUES LESS THAN (734899) ENGINE = InnoDB,
 PARTITION p201202 VALUES LESS THAN (734928) ENGINE = InnoDB,
 PARTITION p201203 VALUES LESS THAN (734959) ENGINE = InnoDB,
 PARTITION p201204 VALUES LESS THAN (734989) ENGINE = InnoDB,
 PARTITION p201205 VALUES LESS THAN (735020) ENGINE = InnoDB,
 PARTITION p201206 VALUES LESS THAN (735050) ENGINE = InnoDB,
 PARTITION p201207 VALUES LESS THAN (735081) ENGINE = InnoDB,
 PARTITION p201208 VALUES LESS THAN (735112) ENGINE = InnoDB,
 PARTITION p201209 VALUES LESS THAN (735142) ENGINE = InnoDB,
 PARTITION p201210 VALUES LESS THAN (735173) ENGINE = InnoDB,
 PARTITION p201211 VALUES LESS THAN (735203) ENGINE = InnoDB,
 PARTITION p201212 VALUES LESS THAN (735234) ENGINE = InnoDB,
 PARTITION p201301 VALUES LESS THAN (735265) ENGINE = InnoDB,
 PARTITION p201302 VALUES LESS THAN (735293) ENGINE = InnoDB,
 PARTITION p201303 VALUES LESS THAN (735324) ENGINE = InnoDB,
 PARTITION p201304 VALUES LESS THAN (735354) ENGINE = InnoDB,
 PARTITION p201305 VALUES LESS THAN (735385) ENGINE = InnoDB,
 PARTITION p201306 VALUES LESS THAN (735415) ENGINE = InnoDB,
 PARTITION p201307 VALUES LESS THAN (735446) ENGINE = InnoDB,
 PARTITION p201308 VALUES LESS THAN (735477) ENGINE = InnoDB,
 PARTITION p201309 VALUES LESS THAN (735507) ENGINE = InnoDB,
 PARTITION p201310 VALUES LESS THAN (735538) ENGINE = InnoDB,
 PARTITION p201311 VALUES LESS THAN (735568) ENGINE = InnoDB,
 PARTITION p201312 VALUES LESS THAN (735599) ENGINE = InnoDB,
 PARTITION p201401 VALUES LESS THAN (735630) ENGINE = InnoDB,
 PARTITION p201402 VALUES LESS THAN (735658) ENGINE = InnoDB,
 PARTITION p201403 VALUES LESS THAN (735689) ENGINE = InnoDB,
 PARTITION p201404 VALUES LESS THAN (735719) ENGINE = InnoDB,
 PARTITION p201405 VALUES LESS THAN (735750) ENGINE = InnoDB,
 PARTITION p201406 VALUES LESS THAN (735780) ENGINE = InnoDB,
 PARTITION p201407 VALUES LESS THAN (735811) ENGINE = InnoDB,
 PARTITION p201408 VALUES LESS THAN (735842) ENGINE = InnoDB,
 PARTITION p201409 VALUES LESS THAN (735872) ENGINE = InnoDB,
 PARTITION p201410 VALUES LESS THAN (735903) ENGINE = InnoDB,
 PARTITION p201411 VALUES LESS THAN (735933) ENGINE = InnoDB,
 PARTITION p201412 VALUES LESS THAN (735964) ENGINE = InnoDB,
 PARTITION p201501 VALUES LESS THAN (735995) ENGINE = InnoDB,
 PARTITION p201502 VALUES LESS THAN (736023) ENGINE = InnoDB,
 PARTITION p201503 VALUES LESS THAN (736054) ENGINE = InnoDB,
 PARTITION p201504 VALUES LESS THAN (736084) ENGINE = InnoDB,
 PARTITION p201505 VALUES LESS THAN (736115) ENGINE = InnoDB,
 PARTITION p201506 VALUES LESS THAN (736145) ENGINE = InnoDB,
 PARTITION p201507 VALUES LESS THAN (736176) ENGINE = InnoDB,
 PARTITION p201508 VALUES LESS THAN (736207) ENGINE = InnoDB,
 PARTITION p201509 VALUES LESS THAN (736237) ENGINE = InnoDB,
 PARTITION p201510 VALUES LESS THAN (736268) ENGINE = InnoDB,
 PARTITION p201511 VALUES LESS THAN (736298) ENGINE = InnoDB,
 PARTITION p201512 VALUES LESS THAN (736329) ENGINE = InnoDB,
 PARTITION pend VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */;
