CREATE TABLE `product` (
  `product_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品ID',
  `product_together_id` varchar(32) NOT NULL DEFAULT '' COMMENT '共卖产品ID',
  `pl_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品线ID',
  `product_code` varchar(200) NOT NULL DEFAULT '' COMMENT '产品CODE',
  `product_model` varchar(128) DEFAULT NULL COMMENT '产品模型',
  `product_sort_name` varchar(255) DEFAULT NULL,
  `product_date_added` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '产品添加时间',
  `product_last_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `product_date_live` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最新live日期',
  `product_date_live_first` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '第一次live日期',
  `product_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '产品状态，0：正常可用Live，1：草稿draft，2：under review',
  `product_status_last` tinyint(2) DEFAULT NULL COMMENT '上一次产品状态:0（正常可用Live）,1(草稿draft),2(under review)',
  `product_status_last_before` tinyint(2) DEFAULT NULL COMMENT '前一次产品状态:0（正常可用Live）,1(草稿draft),2(under review)',
  `product_ur_last_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '置设UR时间',
  `product_ur_log` varchar(500) NOT NULL DEFAULT '' COMMENT '最后UR时间',
  `product_dis_last_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后Discontinue时间',
  `product_dis_log` varchar(500) NOT NULL DEFAULT '' COMMENT 'Discontinue 原因',
  `product_last_set_N` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后置N时间',
  `product_set_N_log` varchar(255) DEFAULT NULL COMMENT '置N的原因',
  `product_ordered` int(11) NOT NULL DEFAULT '0' COMMENT '产品卖出数量',
  `product_quantity` int(4) DEFAULT NULL COMMENT '产品数量',
  `product_pack_unit` int(11) DEFAULT NULL COMMENT '产品单位',
  `product_length` decimal(10,2) DEFAULT NULL COMMENT '产品长',
  `product_width` decimal(10,2) DEFAULT NULL COMMENT '宽度',
  `product_height` decimal(10,2) DEFAULT NULL COMMENT '高',
  `product_pack_length` decimal(10,2) DEFAULT NULL COMMENT '包装后的长',
  `product_pack_width` decimal(10,2) DEFAULT NULL COMMENT '包装后的宽',
  `product_pack_height` decimal(10,2) DEFAULT NULL COMMENT '包装后的高',
  `product_pack_weight` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '包装的重量g',
  `product_shape` varchar(50) NOT NULL COMMENT '产品形状',
  `product_weight` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '产品重量（单位g）',
  `product_total_weight` decimal(8,2) DEFAULT '0.00' COMMENT '产品总重量',
  `product_net_weight` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '产品净重',
  `product_volume_weight` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '体积重量',
  `amazon_weight` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'amazon重量(g)',
  `product_visible` enum('Y','N') NOT NULL DEFAULT 'Y' COMMENT '是否可见:Y可见,N不可见',
  `product_condition` enum('new','refurbished') DEFAULT NULL COMMENT '物品品质(new,refurbished)',
  `product_is_new` enum('N','Y') NOT NULL DEFAULT 'Y' COMMENT '是否新产品标志',
  `product_cost` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '产品成本',
  `dyn_prod_cost` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '产品动态成本',
  `product_base_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '产品成本价（包括利润）',
  `product_profit` float NOT NULL COMMENT '产品毛利率',
  `warehouse_price` decimal(8,2) DEFAULT '0.00' COMMENT '仓储成本(人民币)',
  `other_price` decimal(8,2) DEFAULT '0.00' COMMENT '特殊服务成本(人民币)',
  `misc1` varchar(3000) DEFAULT '',
  `is_combo_item` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为Combo标识.misc1为空时,设为0;misc1不为空时,设为1;',
  `product_base_ship_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运输成本估价',
  `currency_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '货币ID',
  `product_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0:普通产品;1:耗材',
  `gt_id` int(10) NOT NULL COMMENT '产品类型（属性库）',
  `product_ebay_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '产品EBAY状态（0：正常;1：不正常;2：eBay违规）',
  `product_ad_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否有广告（0:无广告，1：有广告）',
  `p_is_ebay_foul` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否EBAY违规',
  `p_is_asr_low` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否ASR较低',
  `p_notification` text NOT NULL COMMENT '销售组公告',
  `ppm_weight_1` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '产品入库包装重量',
  `ppm_weight_2` decimal(8,2) NOT NULL DEFAULT '20.00' COMMENT '产品出库包装重量',
  `ppm_weight_3` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '产品其它包装重量',
  `ppm_price_1` decimal(6,3) NOT NULL DEFAULT '0.000' COMMENT '产品入库包装价格',
  `ppm_price_2` decimal(6,3) NOT NULL DEFAULT '0.360' COMMENT '产品出库包装价格',
  `ppm_total_price` decimal(6,3) NOT NULL DEFAULT '0.380' COMMENT '产品耗材总价格',
  `in_package_require` varchar(300) NOT NULL COMMENT '入库包装要求',
  `out_package_require` varchar(300) NOT NULL COMMENT '出库包装要求',
  `other_package` varchar(50) NOT NULL COMMENT '其它包装材料',
  `other_package_explain` varchar(300) NOT NULL COMMENT '其它包装材料说明',
  `easy_to_break` tinyint(1) NOT NULL COMMENT '易碎',
  `easy_to_fold` tinyint(1) NOT NULL COMMENT '易折',
  `easy_to_scratch` tinyint(1) NOT NULL COMMENT '易刮',
  `easy_to_deform` tinyint(1) NOT NULL COMMENT '易变形',
  `easy_to_wear` tinyint(1) NOT NULL COMMENT '易磨损',
  `is_order_products` enum('Y','N') DEFAULT 'N' COMMENT '是否定制，Y定制/N不定制',
  `black_white` enum('N','B','W') DEFAULT 'N' COMMENT '未处理，黑名单，白名单',
  `dispatch_time_max` tinyint(4) NOT NULL COMMENT '发货处理最大天数',
  `dispatch_time_reason` varchar(255) DEFAULT NULL COMMENT '发货处理原因(英文)',
  `is_ebay_sale` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT 'eBay销售平台',
  `is_site_sale` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '网站销售平台',
  `is_site_online` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '是否网站在线',
  `site_buy_limit` int(10) unsigned NOT NULL COMMENT '网站客户起订量限制',
  `is_amazon_sale` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT 'Amazon销售平台',
  `is_amazon_online` tinyint(2) unsigned NOT NULL DEFAULT '1' COMMENT '是否Amazon在线',
  `amazon_buy_limit` int(10) unsigned NOT NULL COMMENT 'Amazon客户起订量限制',
  `is_cff` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '是否已导入CFF',
  `wc_sign_id` varchar(300) NOT NULL DEFAULT '' COMMENT '标记已经处理的销售组',
  `stocktaking_first_time` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'CFF初次盘点时间',
  `stocktaking_last_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'CFF最后盘点更新时间',
  `weight_comment` varchar(300) DEFAULT NULL COMMENT '重量注释',
  `amazon_upc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Amazon UPC',
  `brand` varchar(255) DEFAULT '' COMMENT '品牌名称',
  `color` varchar(255) DEFAULT '' COMMENT '颜色',
  `yardage` varchar(255) DEFAULT '' COMMENT '尺码尺寸',
  `material` varchar(255) DEFAULT '' COMMENT '材质',
  `owner` varchar(20) NOT NULL DEFAULT '思睿' COMMENT '产品所有人',
  `pack_remark` varchar(255) DEFAULT '' COMMENT '产品打包备注',
  `product_create_user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '产品创建人',
  `product_manage_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品销售认领人',
  `product_research_user_id` int(10) NOT NULL DEFAULT '0' COMMENT '产品调研人',
  `product_source_type` tinyint(2) NOT NULL DEFAULT '1' COMMENT '1.调研自主开发；2.供应商召回；3.鹰眼系统询盘开发；4.销售推荐；5.采集系统；6.品牌产品；8.防疫产品；9.独立站产品；10.自动组成数量combo；11.数据组提供；12.正月十五部；13.采集提供组建combo；14.牛魔王；15.星火产品；16.选品软件-keepa；17.PL1000；18.运营采集；19.FBA开品；20.线下开品；21.汽配主题; 22.大精品; 23.主题推荐; 24.大健云仓; 25.赛盈平台',
  `is_csp_create` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '是否为CSP创建',
  `is_assign_sales_group` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '是否分配销售组',
  `product_mark` int(10) NOT NULL DEFAULT '0' COMMENT '产品标记：1=>11|2=>Gmarket|4=>Auction',
  `sale_by_actual_stock` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '是否按照实际库存销售',
  `product_title` varchar(500) NOT NULL DEFAULT '' COMMENT '标题（用于生产广告标题）',
  PRIMARY KEY (`product_id`) USING BTREE,
  KEY `Index_p_pl_id` (`pl_id`) USING BTREE,
  KEY `index_product_together_id` (`product_together_id`) USING BTREE,
  KEY `index_product_last_modified` (`product_last_modified`) USING BTREE,
  KEY `index_product_date_added` (`product_date_added`) USING BTREE,
  KEY `index_product_date_live` (`product_date_live`) USING BTREE,
  KEY `is_combo_item` (`is_combo_item`,`misc1`(255)) USING BTREE,
  KEY `product_status` (`product_status`,`product_manage_user_id`) USING BTREE,
  KEY `index_live_first` (`product_date_live_first`,`product_ad_status`,`product_id`) USING BTREE,
  KEY `product_source_type` (`product_source_type`) USING BTREE,
  KEY `product_status_2` (`product_status`,`product_visible`,`pl_id`) USING BTREE,
  KEY `product_id` (`product_id`) USING BTREE,
  KEY `index_last_setn_visable` (`product_last_set_N`,`product_visible`) USING BTREE,
  KEY `product_sort_name` (`product_sort_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
