CREATE TABLE `supplier_order_m4x_task` (
  `somt_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `trade_order_code` varchar(32) NOT NULL COMMENT 'istore 订单号',
  `seller_job_number` varchar(32) NOT NULL COMMENT '运营人员工号',
  `platform` varchar(32) NOT NULL COMMENT '平台',
  `download_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '销售订单下载时间',
  `task_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '类型：1-创建PO单；2-重新生单；3-取消；4-SRM推送产品信息',
  `task_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '任务状态：10-待处理；20-处理中；30-处理完成；40-失败；60-销售订单已取消；',
  `task_err_nums` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '失败次数',
  `task_message` text NOT NULL COMMENT '任务备注',
  `is_all_pushed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否产品已全部推送',
  `is_push_dcd` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否推送DCD：1-是；0-否',
  `is_purchase_required` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否需要采购：1-是；0-否',
  `m4x_order_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'M4X 订单类型：1-M4X订单；2-非M4X订单',
  `istore_user_id` int(11) DEFAULT '0' COMMENT '采购istore用户ID',
  `job_number` varchar(64) NOT NULL DEFAULT '' COMMENT '采购工号',
  `purchase_site_id` varchar(64) NOT NULL DEFAULT '' COMMENT '当前销售订单账号',
  `sfc_user_id` int(11) DEFAULT '0' COMMENT '采购权限系统用户ID',
  `is_delete` tinyint(4) DEFAULT '0' COMMENT '是否删除 0-未删除  1-已删除',
  `create_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '创建人用户ID',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后更新时间',
  PRIMARY KEY (`somt_id`),
  KEY `idx_trade_order_code` (`trade_order_code`),
  KEY `idx-purchase_site_id` (`purchase_site_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=227 DEFAULT CHARSET=utf8mb4 COMMENT='m4x销售订单创建PO单任务表';
